### PR TITLE
Separate RemoveSolrCollectionJob from CleanupAccountJob

### LINKED ISSUE #711: CleanupAccountJob is not idempotent
The first time it runs it can successfully remove the Solr endpoint and fail to remove the fedora endpoint.  Then if the job is rerun, it will fail when it can't find the solr endpoint (that it removed on the previous run).

### PR DESCRIPTION
**Pull request by jcoyne**
This improves the idempotency of CleanupAccountJob

Fixes #711

### CODE REVIEW

File: app/jobs/remove_solr_collection_job.rb [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+  # @option connection_options [String] :url
+  # @option connection_options [String] :url
+  def perform(collection, connection_options)
+    solr_client(connection_options).get '/solr/admin/collections', params: { action: 'DELETE', name: collection }
+  end
+
+  private
+
+    def solr_client(connection_options)
+      RSolr.connect(connection_options)
```
Comment (mjgiarlo) [inline app/jobs/remove_solr_collection_job.rb]: We used to use `Blacklight.default_index.connection` to get the connection information. Can you say why we are moving away from that in this PR?

Comment (jcoyne) [inline app/jobs/remove_solr_collection_job.rb]: The Blacklight.default_index is mutable (changed by Account#switch). Since we're moving the solr call to a time after the account record has been deleted, we need to make it immutable.
