### PR TITLE
Mount QuestioningAuthority

### LINKED ISSUE #736: [HyBox/production] ActionView::Template::Error: undefined method `qa_path' for #<Module:0x007fef508427d0>
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/32594829)

### LINKED ISSUE #737: [HyBox/production] ActionView::Template::Error: undefined method `qa_path' for #<Module:0x0056483c868230>
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/32594831)

### PR DESCRIPTION
**Pull request by jcoyne**
Fixes #736 Fixes #737

### CODE REVIEW

File: config/routes.rb [hunk 1]
```diff
@@ -17,6 +17,7 @@
   get 'splash', to: 'splash#index'
   get 'status', to: 'status#index'
   devise_for :users
+  mount Qa::Engine => '/authorities'
```
Comment (mjgiarlo) [inline config/routes.rb]: Should Hyrax be generating this line? How'd we miss this?

Comment (jcoyne) [inline config/routes.rb]: Hyrax has a generator for it. I don't know how we missed it though.

Comment (jcoyne) [inline config/routes.rb]: Looks like it was in the sufia upgrade generator, so we never ran it.  https://github.com/projecthydra-labs/hyrax/commit/75f94af30aa228d4adf9878d3f144d232a8dcfb9
